# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('en_name', models.CharField(default='', max_length=64, verbose_name='英文名（可选）')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (3, '其他')], verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='出生日期')),
                ('birth_area', models.CharField(default='', max_length=128, verbose_name='出生地')),
                ('profession', models.CharField(default='', max_length=16, verbose_name='职业')),
            ],
            options={
                'verbose_name': '人物',
            },
        ),
        migrations.CreateModel(
            name='CelebrityPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Celebrity', verbose_name='人')),
            ],
            options={
                'verbose_name': '人物图片',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='电影标题')),
                ('initial_release_date', models.DateField(null=True, verbose_name='上映日期')),
                ('runtime', models.IntegerField(null=True, verbose_name='片长(分钟)')),
                ('languages', models.CharField(max_length=255, verbose_name='语言')),
                ('other_title', models.CharField(max_length=255, verbose_name='又名')),
                ('country', models.CharField(max_length=16, verbose_name='制片国家/地区')),
                ('director', models.ManyToManyField(related_name='directors', to='movies.Celebrity', verbose_name='导演')),
                ('scriptwriter', models.ManyToManyField(related_name='scriptwriters', to='movies.Celebrity', verbose_name='编剧')),
            ],
            options={
                'verbose_name': '电影',
            },
        ),
        migrations.CreateModel(
            name='MovieBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(verbose_name='简介')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': '电影简介',
            },
        ),
        migrations.CreateModel(
            name='MoviePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '剧照',
            },
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='正文')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='电影')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '影评',
            },
        ),
    ]
