# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scriptwriter',
            new_name='scriptwriters',
        ),
    ]
