# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170301_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='birth_area',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='出生地'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='en_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='英文名（可选）'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='职业'),
        ),
    ]
