# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170301_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField(verbose_name='标签名称')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '标签',
            },
        ),
    ]
